version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - ECR_REPO=379767357976.dkr.ecr.us-east-2.amazonaws.com/usm
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ${ECR_REPO}:${CODEBUILD_BUILD_NUMBER} .
      - docker tag ${ECR_REPO}:${CODEBUILD_BUILD_NUMBER} ${ECR_REPO}:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push ${ECR_REPO}:latest
      - echo push "Done".
      - echo Writing image definitions file...
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
